In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
movies_kg_df = pd.read_csv('merged_movies/kg_movies.csv')
series_kg_df = pd.read_csv('merged_tvshows/tv_shows.csv')
net_df = pd.read_csv('netflix/netflix_titles.csv')
amazon_df = pd.read_csv('amazon/amazon_prime_titles.csv')
disney_df = pd.read_csv('disney/disney_plus_titles.csv')
hulu_df = pd.read_csv('hulu/hulu_titles.csv')

In [3]:
movies_kg_df

,Unnamed: 0,ID,Title,Year,Age,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type
0,0,1,The Irishman,2019,18+,98/100,1,0,0,0,0
1,1,2,Dangal,2016,7+,97/100,1,0,0,0,0
2,2,3,David Attenborough: A Life on Our Planet,2020,7+,95/100,1,0,0,0,0
3,3,4,Lagaan: Once Upon a Time in India,2001,7+,94/100,1,0,0,0,0
4,4,5,Roma,2018,18+,94/100,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
9510,9510,9511,Most Wanted Sharks,2020,NaN,14/100,0,0,0,1,0
9511,9511,9512,Doc McStuffins: The Doc Is In,2020,NaN,13/100,0,0,0,1,0
9512,9512,9513,Ultimate Viking Sword,2019,NaN,13/100,0,0,0,1,0
9513,9513,9514,Hunt for the Abominable Snowman,2011,NaN,10/100,0,0,0,1,0
9514,9514,9515,Women of Impact: Changing the World,2019,7+,10/100,0,0,0,1,0

In [12]:
def in_strem(data, str, str2 =None, str3 = None):
    if str2 == None and str3 == None:
        return data.loc[data[str] == 1]
    elif str2 != None and str3 == None:
        return data.loc[(data[str] == 1) | (data[str2] == 1)]
    elif str2 != None and str3 != None:
        return data.loc[(data[str] == 1) | (data[str2] == 1) | (data[str3] == 1)]

In [5]:
def just_in(data , str,  str2 =None, str3 = None):
    stream = ['Disney+', 'Netflix', 'Hulu', 'Prime Video']
    stream.remove(str)

    if str2 == None and str3 == None:
        unico = data.loc[(data[str] == 1) & (data[stream[0]] == 0) & (data[stream[1]] == 0) & (data[stream[2]] == 0)]
        
    elif str2 != None and str3 == None:
        stream.remove(str2)
        unico = data.loc[(data[str] == 1) & (data[str2] == 1) & (data[stream[0]] == 0) & (data[stream[1]] == 0)]
    
    elif str2 != None and str3 != None:
        stream.remove(str3)
        unico = data.loc[(data[str] == 1) & (data[str2] == 1) & (data[str3] == 1) & (data[stream[0]] == 0)]
    
    return unico